# Generated by Django 3.2.5 on 2023-02-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='year_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.ManyToManyField(to='academics.branch')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.year')),
            ],
        ),
    ]
