# Generated by Django 3.2.5 on 2023-02-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_year_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academics.branch')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academics.year')),
            ],
        ),
        migrations.DeleteModel(
            name='year_branch',
        ),
    ]
