# Generated by Django 3.2.5 on 2023-02-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20230211_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='academics.branch'),
        ),
    ]
