# Generated by Django 3.2.5 on 2023-02-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_courses_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.FileField(upload_to='academics/documents')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academics.document_type')),
            ],
        ),
    ]
