# Generated by Django 3.2.5 on 2023-02-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_type',
            name='image',
            field=models.ImageField(default='', upload_to='academics/images'),
        ),
    ]
